<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?= $route ?> - Blog</title>
</head>
<body style="font-family: Arial; text-align: center;">
	<header>
		<nav>
			<a href="?page=home">Home</a>
			<a href="?page=create">Créer un article</a>
		</nav>
	</header>

	<main>
		<?php require './controllers/' . $route . '_controller.php'; ?>
	</main>

	<footer>
		Blog - Coda © 2023
	</footer>
</body>
</html>