<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?= $route ?> - Blog</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
</head>
<body style="font-family: Arial;">
	<header class="container is-max-desktop">
		<nav class="navbar" role="navigation" aria-label="main navigation">
			<a class="navbar-item" href="?page=home">Home</a>
			<a class="navbar-item" href="?page=create">Créer un article</a>
		</nav>
	</header>

	<main class="container is-max-desktop">

		<section class="section">
			<?php require './controllers/' . $route . '_controller.php'; ?>
		</section>
	</main>

	<footer class="footer content has-text-centered">
		Blog - Coda © 2023
	</footer>
</body>
</html>