<h1 class="title is-2">Se connecter</h1>

<form action="index.php?page=login" method="post">

    <div class="field">
        <label for="username">Nom d'utilisateur</label><br>
        <input class="input" type="text" name="username" id="username" placeholder="20 caractères maximum"
            maxlength="20">
    </div>


    <div class="field">
        <label for="password">Mot de passe</label><br>
        <input class="input" type="password" name="password" id="password" placeholder="20 caractères maximum"
            maxlength="20">
    </div>

    <button class="button is-link" type="submit">Se connecter</button>

</form>