<h1 class="title is-2">S'inscrire</h1>

<form action="index.php?page=register" method="post">

    <div class="field">
        <label for="username">Nom d'utilisateur</label><br>
        <input class="input" type="text" name="username" id="username" placeholder="20 caractères maximum"
            maxlength="20">
    </div>

    <div class="field">
        <label for="email">Adresse email</label><br>
        <input class="input" type="email" name="email" id="email" placeholder="50 caractères maximum"
            maxlength="50">
    </div>

    <div class="field">
        <label for="password">Mot de passe</label><br>
        <input class="input" type="password" name="password" id="password" placeholder="20 caractères maximum"
            maxlength="20">
    </div>

    <div class="field">
        <label for="password_confirm">Confirmez le mot de passe</label><br>
        <input class="input" type="password" name="password_confirm" id="password_confirm"
            placeholder="20 caractères maximum" maxlength="20">
    </div>

    <button class="button is-link" type="submit">S'inscrire</button>

</form>